[project]
name="bakrianoo-mini-rag"
version="0.1.0"
dependencies = [
    "fastapi>=0.121.1",
    "python-dotenv>=1.2.1",
    "python-multipart>=0.0.20",
    "uvicorn[standard]>=0.38.0",
]

[dependency-groups]
dev = [
    "black>=25.11.0",
    "flake8>=7.3.0",
    "isort>=7.0.0",
    "tox>=4.32.0",
]
