"""initial commit

Revision ID: 263426708036
Revises: 
Create Date: 2025-12-26 20:53:57.142322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '263426708036'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('projectid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('projectid'),
    sa.UniqueConstraint('project_uuid')
    )
    op.create_table('assets',
    sa.Column('assetid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_uuid', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('asset_size', sa.Integer(), nullable=False),
    sa.Column('asset_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_projectid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_projectid'], ['projects.projectid'], ),
    sa.PrimaryKeyConstraint('assetid'),
    sa.UniqueConstraint('asset_uuid')
    )
    op.create_index('idx_asset_project_id', 'assets', ['asset_projectid'], unique=False)
    op.create_index('idx_asset_type', 'assets', ['asset_type'], unique=False)
    op.create_table('chunks',
    sa.Column('chunkid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_uuid', sa.UUID(), nullable=False),
    sa.Column('chunk_text', sa.String(), nullable=False),
    sa.Column('chunk_order', sa.Integer(), nullable=False),
    sa.Column('chunk_projectid', sa.Integer(), nullable=False),
    sa.Column('chunk_assetid', sa.Integer(), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chunk_assetid'], ['assets.assetid'], ),
    sa.ForeignKeyConstraint(['chunk_projectid'], ['projects.projectid'], ),
    sa.PrimaryKeyConstraint('chunkid'),
    sa.UniqueConstraint('chunk_uuid')
    )
    op.create_index('idx_chunk_asset_id', 'chunks', ['chunk_assetid'], unique=False)
    op.create_index('idx_chunk_project_id', 'chunks', ['chunk_projectid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chunk_project_id', table_name='chunks')
    op.drop_index('idx_chunk_asset_id', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('idx_asset_type', table_name='assets')
    op.drop_index('idx_asset_project_id', table_name='assets')
    op.drop_table('assets')
    op.drop_table('projects')
    # ### end Alembic commands ###
